### ISSUE TITLE
Do not work on Mac OS

### ISSUE THREAD

**Issue by sgrillon14** [profesorfalken/jSensors#12]
??

**Comment by profesorfalken** [comment]
Hello, 

No. Only Windows&Linux are supported based on openhardwaremonitor dlls and lm_sensors libraries.

I do not know anything about MacOS systems, but if someone want to make a pull request...


Best regards

**Comment by sgrillon14** [comment]
I find a workaround: [https://github.com/oshi/oshi](https://github.com/oshi/oshi)
