### ISSUE TITLE
can't read the templature

### ISSUE THREAD

**Issue by helloworld28** [profesorfalken/jSensors#7]
can't read the templature, output is 
"
Found CPU component: Intel Core i5-3320M
Sensors: 
Temp CPU Core #1: 0.0 C
Temp CPU Core #2: 0.0 C
Temp CPU Package: 0.0 C
Load CPU Core #1: 35.22728
Load CPU Core #2: 26.13636
Load CPU Total: 30.68182
Load Memory: 74.63326
Found disk component: Generic Hard Disk
Sensors: 
Load Used Space: 83.86135
", my OS is window 10

**Comment by AndreiD** [comment]
same

**Comment by profesorfalken** [comment]
Hello, 

Have you run the application as administrator?

Regards

**Comment by Tuupertunut** [comment]
Running as admin fixed this for me. If you are running this in an IDE, start the IDE as admin.
